In [2]:
import numpy as np

In [5]:
#Ejercicio mediana

array_números=np.random.randint(100, size=(10,10))
print(array_números)
print ("La mediana de los números es",np.median(array_números))

[[68  1 22 50 57 93 80 66 46 91]
 [38  6 95 76  9 94 81 69 55 21]
 [50 43 29 74  7 90 53 22  9 50]
 [35 77 83 93 12 71 65 48 19 53]
 [20  1 44 95 44 55 79 44 49 10]
 [76 65 32 72 99 35 30  4 41 85]
 [48 75  7 19 51 90 76 38 17 40]
 [44 70 20 15 92 45 53 34  2 47]
 [33 15 54 11  1 88 69 93 69  9]
 [41 20 65 90 32 86 32 85 80 64]]
La mediana de los números es 49.5


In [21]:
#Ejercicio factorial
array_1=np.random.randint(20)
print("El factorial de",array_1,"es",np.math.factorial(array_1))

El factorial de 6 es 720


In [32]:
#Ejercicio sumatoria

def suma(m,n):
   
    if m<n:
        x=np.array(range(n-m+2))  
    
    else:
        x=np.array(range(m-n+2))
    return x.sum()
    
print("La sumatoria es",suma(1,5))

La sumatoria es 15


In [26]:
#Ejercicio sueldos
from numpy import genfromtxt

array1 = np.genfromtxt("sueldos.txt", delimiter=",")
nan_array= np.isnan(array1)
not_nan_array =~ nan_array
sueldos = array1[not_nan_array] 

In [33]:
media=np.mean(sueldos)
print("La media de los sueldos es", media)
mediana=np.median(sueldos)
print("La mediana de los suelos es", mediana)

La media de los sueldos es 18652846.870649517
La mediana de los suelos es 75000.0
